export const INTERACTION_HIT_SLOP_PX = 10
export const COMPLETION_FEEDBACK_DURATION_MS = 1500
export const PRESET_TASK_FOCUS_SCROLL_OFFSET_PX = 16
export const PRESET_EDITOR_KEYBOARD_EXTRA_SCROLL_PADDING_PX = 96
